package com.example.groupgsecurityca.RSA;

/*

Sean Byrne (23343362)

This class first generates a public, private key value pair for each client
also handles the encryption and decryption
of the shared AES key used encrypt the messages send between the
clients within the in the application

 */

import java.security.*;
import java.util.Base64;
import javax.crypto.Cipher;

public class RSAEncryption {

    private KeyPair keyPair;

    /*

    Generate a new RSA key pair for each client.
    Initializes a KeyPairGenerator with the RSA algorithm with the key size of 1024 bits
    stores instance within the keyPair variable
    called once per client to create their unique encryption keypair

     */
    public void generateKeypair() throws Exception {
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
        keyPairGenerator.initialize(1024);
        keyPair = keyPairGenerator.generateKeyPair();
    }
    /*
    retrieves the public key generated by the key pair
    used to be shared with other clients over the server to encrypt the AES key
     */
    public PublicKey getPublicKey(){
        return keyPair.getPublic();
    }

    /*
    retrieves teh private key generated by the key pair
    used for decrypting the encrypted AES key
    must be kept secret and not to be shared to anyone
     */
    public PrivateKey getPrivateKey(){
        return keyPair.getPrivate();
    }

    /*
    encrypts the AES using a specified public key
    uses RSA along with ECB/OAEPWithSHA-256AndMGF1Padding for secure encryption
    used for encrypting the AES key before sending it to the recipient
     */
    public byte[] encryptKey(byte[] data, PublicKey publicKey) throws Exception {
        Cipher cipher = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");
        cipher.init(Cipher.ENCRYPT_MODE, publicKey);
        return cipher.doFinal(data);
    }

    /*
    decrypts the AES using the clients specific private key
    Uses RSA with ECB/OAEPWithSHA-256AndMGF1Padding to reverse the encryption process
    restores the original AES key to be used for encrypting and decrypting the send Messages between clients
     */
    public byte[] decryptKey(byte[] data) throws Exception {
        Cipher cipher = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");
        cipher.init(Cipher.DECRYPT_MODE,  keyPair.getPrivate());
        return cipher.doFinal(data);
    }


    /*
    retrives the public key encoded in base64 string for easier message transfer
    converts the public key into text format using base64 encoding
     */
    public String getPublicKeyBase64(){
        return Base64.getEncoder().encodeToString(getPublicKey().getEncoded());
    }
}
